### ISSUE TITLE
bundle install issue

### ISSUE THREAD

**Issue by osallou** [gwdg/rOCCI-server#84]
Hi,
I try to install from source but I have a bundle install issue:

    You are trying to install in deployment mode after changing
    your Gemfile. Run `bundle install` elsewhere and add the
    updated Gemfile.lock to version control.
    
    You have added to the Gemfile:
    * debugger

    You have deleted from the Gemfile:
    * byebug

I tried to regenerate Gemfile.lock to fix this, but when I run again the command, it says that it is ok, but vendor/bundle remains empty (no gem). This leads to error forthe passenger step.

It is also advised to not run Bundler as root.

**Comment by osallou** [comment]
running before:

    bundle install --no-deployment --without development test

seems to fix the issue

but passenger command fails:

     bundle exec passenger-install-apache2-module --auto

...
 * Checking for Curl development headers with SSL support...
--------------------------------------------
*** EXCEPTION: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/tmp/passenger.euspy2" (parent directory mode 40777) (ArgumentError)
    /usr/lib/ruby/1.9.1/fileutils.rb:708:in `remove_entry_secure'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/utils/tmpio.rb:72:in `ensure in mktmpdir'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/utils/tmpio.rb:72:in `mktmpdir'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info.rb:159:in `create_temp_file'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info/compiler.rb:218:in `find_header'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info/depcheck_specs/libs.rb:30:in `block (2 levels) in load'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info/depcheck.rb:77:in `call'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info/depcheck.rb:77:in `check'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info/depcheck.rb:321:in `block in check_all'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info/depcheck.rb:317:in `each'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/platform_info/depcheck.rb:317:in `check_all'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/abstract_installer.rb:150:in `check_dependencies'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/bin/passenger-install-apache2-module:126:in `run_steps'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/lib/phusion_passenger/abstract_installer.rb:72:in `run'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/gems/passenger-4.0.59/bin/passenger-install-apache2-module:866:in `<top (required)>'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/bin/passenger-install-apache2-module:23:in `load'
    /opt/rOCCI-server/vendor/bundle/ruby/1.9.1/bin/passenger-install-apache2-module:23:in `<main>'

--------------------------------------------

Oops, something went wrong :-(

**Comment by arax** [comment]
Hi,

using Ruby 1.9.3 is not recommended anymore (use 2+, `debugger` installation will not be attempted there). Our lock files are generated for the 2+ environment, hence the dependency clash.

Ad. the passenger build failure, what are the permissions on your `/tmp` directory? It looks like you are missing the sticky bit there (`1777/drwxrwxrwt` vs. your `0777/drwxrwxrw-`).

Cheers

**Comment by osallou** [comment]
Thanks but documentation specifies ruby 1.9.3+
Regarding tmp i will have a look but:

* There is nothing specified in doc about this
* /tmp should not require any rights nor modification as a system directory.

For info i am on Debian Wheezy, documation set it as a tested OS.

Le mer. 16 sept. 2015 21:54, Boris Parak <notifications@github.com> a
écrit :

**Comment by arax** [comment]
On Wednesday, September 16, 2015, Olivier Sallou <notifications@github.com>
wrote:

> Thanks but documentation specifies ruby 1.9.3+


Correct. The wiki documentation for installation from source has not been
updated yet. Installation from source is a fallback/developer solution and
as such it presumes a certain level of experience with ruby dev stacks and
tools. Updating the requirement to 2+ would mean including RVM guides or
dropping support for all systems not offering that ruby by default ... One
way or another, you should install the server from packages whenever
possible unless you have a very good reason not to do so.


> Regarding tmp i will have a look but:
>
> * There is nothing specified in doc about this
> * /tmp should not require any rights nor modification as a system
> directory.


The sticky bit on tmp is not just the default but also a very important
part of tmp function. Having tmp with 0777 without it is a serious security
flaw compromising the intgrity of your entire system. This usually happens
when you have tmp on a separate block device and you forgot to change the
permissions after the firts mount.


>
> For info i am on Debian Wheezy, documation set it as a tested OS.


Yes, primarily for installation from packages. We will do our best to keep
the documentation up-to-date in the future.

**Comment by osallou** [comment]
thanks a lot

**Comment by osallou** [comment]
You may also want to update page:

http://gwdg.github.io/rOCCI-server/

about install insctructions

**Comment by arax** [comment]
Fixed. Thanks!
