### ISSUE TITLE
authentication errors

### ISSUE THREAD

**Issue by osallou** [gwdg/rOCCI-server#85]
hi,
I have installed occi-server via packages. Configuration is done and server is running with opennebula backend.
I tried the basic test but it fails with authentication:

    curl --insecure -u 'rocci:xxxx' https://localhost:11443/-/
    Authentication failed! The following strategies are supported "voms, x509, basic"

I am using basic authentication.

If I look at HTTP messages between occi and opennebula, I can see the user_pool_cache request to get the list  of users (from update_userpool_cache in cloud_auth_client.rb) , and the answer message that contains the list of users (so looks fine till here).

However, the user pool cache seems to remain empty. I added a few logs to debug

          @user_pool = ::OpenNebula::UserPool.new(oneadmin_client)
          Rails.logger.info "[OSALLOU] iterate userpool_cache"  <= this message appears in log
          @user_pool.each do |user|
            Rails.logger.info "[OSALLOU] userpool_cache: "+user.to_s <= this message never appears
          end

@user_pool is shown as a OpenNebula::UserPool, but it seems to be empty at this step.

As a result, authentication fails because it does not find any password for the user to compare with input password.

How can I debug this?

**Comment by osallou** [comment]
I saw that info is retreive at user_pool.info, so I added a new log, and return of user_pool.info is Nil

          rc = @user_pool.info
          rc.each do |user|
             Rails.logger.info "[OSALLOU] user: "+user.to_s
          end

rc = Nil

**Comment by arax** [comment]
Hi,

which version of OpenNebula is on the other side of that info call? Did you correctly set up the server admin user account for rOCCI-server?

In OCA, you cannot iterate over `rc`, you have to iterate over `user_pool`.

**Comment by osallou** [comment]
I use opennebula 4.8

Ok, I have added log on user_pool iteration after .info call and I see all users. So cache setup is fine.
However, in cloud_auth/basic_cloud_auth.rb it cannot get the password:

    def do_auth(params = {})
      Rails.logger.info "[OSALLOU] do_auth"
      fail Backends::Errors::AuthenticationError, 'Credentials for Basic not set!' unless params && params[:username] && params[:password]
      Rails.logger.info "[OSALLOU] get_password for "+params[:username]
      one_pass = get_password(params[:username], 'core')
      Rails.logger.info "[OSALLOU] "+one_pass.to_s+" ?= "+::Digest::SHA1.hexdigest(params[:password]) 

In last log, one_pass is empty

2015-09-17 11:13:46.700 [ INFO  ] [ded2c223-8066-41d0-b33c-cc60faeba205] [OSALLOU]  ?= mysha1encryptedpassword (pid:19614)
2015-09-17 11:13:46.700 [ WARN  ] [ded2c223-8066-41d0-b33c-cc60faeba205] [Backend] Failed to authenticate user: User could not be authenticated! (pid:19614)

**Comment by arax** [comment]
When you run `oneuser show NAME` on the same account in OpenNebula, do you see an output similar to:
```bash
NAME            :  xxxxxxxxxxxxxx
#...               
PASSWORD        : xxxxxxxxxxxxxx
#...
AUTH_DRIVER     : core 
```
?

What is the username here? Any special characters?

**Comment by osallou** [comment]
I was trying with rocci user itself, and 

    ID              : 111
    NAME            : rocci
    GROUP           : oneadmin
    PASSWORD        : xx
    AUTH_DRIVER     : server_cipher
    ENABLED         : Yes

its driver is not core. If I try with an user, who is "core" driver, it seems to work (getting many schema info lines).

So ok, admin users are specific, and it does not work with those users.

**Comment by arax** [comment]
Yes. Any kind of "plain" (username/password-based) authentication is strictly mapped to 'core'.
