### ISSUE TITLE
there's no nginx docs to be found

### ISSUE THREAD

**Issue by FlorianHeigl** [gwdg/rOCCI-server#86]
Hi,

earlier references were to https://github.com/gwdg/rOCCI-server#nginx but this page is gone.
Otherwise there's just statements that nginx is supported, but nowhere is info how to set it up.

I'm trying, but it's sure confusing :-)

**Comment by arax** [comment]
Hi,

rOCCI-server is just a Rack-compliant application, you can deploy it with any Rack-compliant application server. Our documentation deals only with Apache these days, as that is the most popular choice with our users. You can use this guide [1] to set up Passenger for Nginx. Here is a configuration file example:
~~~
server {
    listen 80;
    server_name yourserver.com;

    # Tell Nginx and Passenger where rOCCI-server's 'public' directory is
    root /opt/rOCCI-server/public;

    # Turn on Passenger
    passenger_enabled on;
    passenger_ruby /path-to-ruby;
}
~~~
Some advanced features may not be available when running with Nginx (mostly authentication modules, X.509+VOMS for example).

As rOCCI-server (in production mode) is configured using ENV variables passed down from Apache [2], you should definitely explore the use of `passenger_env_var` [3] in your configuration file.

[1] https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/nginx/oss/install_passenger_main.html
[2] https://github.com/EGI-FCTF/rOCCI-server/blob/master/etc/production.yml
[3] https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_env_var

**Comment by FlorianHeigl** [comment]
Hi,

I think that should help a lot. Thank you. Please could you take care to at least reference this?
Obviously noone will chose nginx if it's documented. ;)

Normally I'd also have gone with Apache but nginx was already in place and working so didn't make sense to switch. But I also know a few younger admins who know nginx a lot better than apache. lure them in!

**Comment by arax** [comment]
Hi,

thanks for your feedback! We can definitely include a few pointers on how to use rOCCI-server with Nginx, however it could take a while to get that documentation on par with the one for Apache. Stay tuned!
